guru:
    jms:
        username: JMS Username..........
        password: somepass.........
        url: SomeUrl.........

---
spring:
  profiles:
    active: de

guru:
  jms:
    username: JMS Username.....$$$$.....
    password: somepass.....$$$.....
    url: SomeUrl....$$$.....